allow_r2_trades = false
alpha1_mantissa = 40
alpha2_mantissa = 40
alpha3_mantissa = 20
alpha_exponent = -2
base_position_mantissa = 1000000
cooldown_after_exit_ms = 1000
min_d_perp_mantissa = 520
min_fragility_mantissa = 78
min_hold_ms = 3000
min_toxicity_mantissa = 11
price_exponent = -2
qty_exponent = -8
slip_cap_ticks = 2
tau_confidence_mantissa = 50
tau_d_perp_mantissa = 200
tau_dir_enter = 2
tau_dir_exit = 1
tau_fragility_mantissa = 60
tau_fti_persist_mantissa = 30
tau_toxicity_persist_mantissa = 30
threshold_exponent = -2
tick_size_mantissa = 10
u_aggressive_mantissa = 75
urgency_d_perp_mantissa = 40
urgency_exponent = -2
urgency_fragility_mantissa = 40
urgency_toxicity_mantissa = 20
